# https://support.codacy.com/hc/en-us/articles/115000566729-How-do-I-ignore-files-that-are-not-in-master-branch-
exclude_paths:
  - assets/**/*
  - css/**/*
  - css/boots*
  - vendor/**/*
  - js/bootstrap*
  - js/bootst**/*
  - js/npm.js
  - tests/**.php
