language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install

script: 
  - phpunit -c phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
